In [1]:
import numpy as np

In [2]:
x = np.arange(8, dtype=np.int8)

In [3]:
x.strides

(1,)

In [4]:
x.shape = 4, 2

In [5]:
x.strides

(2, 1)

In [6]:
(x == x).all()

True

In [7]:
(x == x).sum()

8

In [8]:
x.sum()

28

In [9]:
x.itemsize

1

In [10]:
x.nbytes

8

In [11]:
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]], dtype=int8)

In [12]:
x.shape

(4, 2)

In [13]:
x.strides

(2, 1)

In [16]:
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int8)

In [19]:
np.array(
    x.flat
)

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int8)

In [20]:
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]], dtype=int8)

In [23]:
np.swapaxes(x, 0, 1)

array([[0, 2, 4, 6],
       [1, 3, 5, 7]], dtype=int8)

In [24]:
x.max()

7

In [25]:
x.max(axis=0)

array([6, 7], dtype=int8)

In [27]:
x.min(axis=1)

array([0, 2, 4, 6], dtype=int8)

In [28]:
x * x

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49]], dtype=int8)

In [29]:
x * 2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]], dtype=int8)

In [30]:
x * [2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

In [31]:
x * [2,2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

In [32]:
x * [2,2,2,2]

ValueError: operands could not be broadcast together with shapes (4,2) (4,) 

In [33]:
x * [2,2,2]

ValueError: operands could not be broadcast together with shapes (4,2) (3,) 

In [34]:
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]], dtype=int8)

In [35]:
l = [1,2,3,4]
l

[1, 2, 3, 4]

In [36]:
ll = l[1:-1]
ll

[2, 3]

In [37]:
ll[0] = 99
ll

[99, 3]

In [38]:
l

[1, 2, 3, 4]

In [40]:
np.random.randint(10)

7

In [41]:
np.random.randint(1,20, (3,3))

array([[ 3,  2,  5],
       [11,  1, 19],
       [11,  4,  7]])

In [42]:
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]], dtype=int8)

In [45]:
x[0, :] = 8

In [46]:
x

array([[8, 8],
       [2, 3],
       [4, 5],
       [6, 7]], dtype=int8)

In [47]:
x[ : , 0 ] = 8

In [48]:
x

array([[8, 8],
       [8, 3],
       [8, 5],
       [8, 7]], dtype=int8)

In [49]:
slice

slice

In [50]:
x.ndim

2

In [51]:
Ellipsis

Ellipsis

In [52]:
Ellipsis == ...

True

In [53]:
x[..., 0]

array([8, 8, 8, 8], dtype=int8)

In [54]:
x[0, ...]

array([8, 8], dtype=int8)

In [55]:
...

Ellipsis

In [59]:
x[None, ..., np.newaxis, None]

array([[[[[8]],

         [[8]]],


        [[[8]],

         [[3]]],


        [[[8]],

         [[5]]],


        [[[8]],

         [[7]]]]], dtype=int8)

In [60]:
a = np.arange(10)

In [61]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
a[:, None]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [63]:
a[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [64]:
a[None, :]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [65]:
a[:, np.newaxis, None]

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]],

       [[7]],

       [[8]],

       [[9]]])

In [66]:
a[:, None] + a[None, :]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [67]:
np.arange(0,9,-1)

array([], dtype=int32)

In [68]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [69]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
a[ [1,2,3,4] ]

array([1, 2, 3, 4])

In [71]:
a[(1,2,3,4)]

IndexError: too many indices for array: array is 1-dimensional, but 4 were indexed

In [72]:
a[np.array([1,2,3,4])]

array([1, 2, 3, 4])

In [73]:
a[ (1,2,3,4), ]

array([1, 2, 3, 4])

In [74]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
a.shape = 2, 5

In [76]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [77]:
a[ [True, True], : ]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [78]:
a[ [False, False], : ]

array([], shape=(0, 5), dtype=int32)

In [80]:
a[ [True, True, False, False], : ]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 4

In [81]:
a[ [True, False], : ]

array([[0, 1, 2, 3, 4]])

In [82]:
np.nan

nan

In [83]:
a[a<5]

array([0, 1, 2, 3, 4])

In [85]:
a[a<5].nonzero()

(array([1, 2, 3, 4], dtype=int64),)

In [88]:
np.linspace(3,4,5)

array([3.  , 3.25, 3.5 , 3.75, 4.  ])

In [89]:
numbers = np.linspace(1, 50, 24).reshape(4, -1)
numbers

array([[ 1.        ,  3.13043478,  5.26086957,  7.39130435,  9.52173913,
        11.65217391],
       [13.7826087 , 15.91304348, 18.04347826, 20.17391304, 22.30434783,
        24.43478261],
       [26.56521739, 28.69565217, 30.82608696, 32.95652174, 35.08695652,
        37.2173913 ],
       [39.34782609, 41.47826087, 43.60869565, 45.73913043, 47.86956522,
        50.        ]])

In [90]:
numbers = np.linspace(1, 50, 24, dtype=np.int8).reshape(4, -1)
numbers

array([[ 1,  3,  5,  7,  9, 11],
       [13, 15, 18, 20, 22, 24],
       [26, 28, 30, 32, 35, 37],
       [39, 41, 43, 45, 47, 50]], dtype=int8)

In [91]:
mask = numbers % 4 == 0

In [92]:
mask

array([[False, False, False, False, False, False],
       [False, False, False,  True, False,  True],
       [False,  True, False,  True, False, False],
       [False, False, False, False, False, False]])

In [93]:
numbers[mask]

array([20, 24, 28, 32], dtype=int8)

In [95]:
np.random.default_rng().standard_normal(1000).std()

1.0037480739115765

In [96]:
np.random.default_rng().standard_normal(1000)[:5]

array([-0.71542903, -0.55030224,  1.11074803,  0.23466803, -1.91453917])

In [97]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [98]:
a.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [99]:
a.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [100]:
np.sort(a)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [101]:
np.sort(a, axis=None)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [103]:
np.sort(a, axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [104]:
np.sort(a, axis=1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [105]:
a = np.array([
    [1,2,5,1,8,4,3],
    [6,1,7,9,2,0,3]
])

In [106]:
np.sort(a, axis=1)

array([[1, 1, 2, 3, 4, 5, 8],
       [0, 1, 2, 3, 6, 7, 9]])

In [107]:
np.sort(a, axis=0)

array([[1, 1, 5, 1, 2, 0, 3],
       [6, 2, 7, 9, 8, 4, 3]])

In [109]:
np.concatenate((a,a))

array([[1, 2, 5, 1, 8, 4, 3],
       [6, 1, 7, 9, 2, 0, 3],
       [1, 2, 5, 1, 8, 4, 3],
       [6, 1, 7, 9, 2, 0, 3]])

In [110]:
a

array([[1, 2, 5, 1, 8, 4, 3],
       [6, 1, 7, 9, 2, 0, 3]])

In [111]:
np.sort(a)

array([[1, 1, 2, 3, 4, 5, 8],
       [0, 1, 2, 3, 6, 7, 9]])

In [112]:
np.sort(a, axis=1)

array([[1, 1, 2, 3, 4, 5, 8],
       [0, 1, 2, 3, 6, 7, 9]])

In [115]:
np.concatenate((a,a))

array([[1, 2, 5, 1, 8, 4, 3],
       [6, 1, 7, 9, 2, 0, 3],
       [1, 2, 5, 1, 8, 4, 3],
       [6, 1, 7, 9, 2, 0, 3]])

In [116]:
np.concatenate((a,a),axis=0)

array([[1, 2, 5, 1, 8, 4, 3],
       [6, 1, 7, 9, 2, 0, 3],
       [1, 2, 5, 1, 8, 4, 3],
       [6, 1, 7, 9, 2, 0, 3]])

In [117]:
np.concatenate((a,a),axis=1)

array([[1, 2, 5, 1, 8, 4, 3, 1, 2, 5, 1, 8, 4, 3],
       [6, 1, 7, 9, 2, 0, 3, 6, 1, 7, 9, 2, 0, 3]])

In [118]:
np.sort(a, axis=1) == np.sort(a)

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [119]:
np.concatenate((a,a,a), axis=None)

array([1, 2, 5, 1, 8, 4, 3, 6, 1, 7, 9, 2, 0, 3, 1, 2, 5, 1, 8, 4, 3, 6,
       1, 7, 9, 2, 0, 3, 1, 2, 5, 1, 8, 4, 3, 6, 1, 7, 9, 2, 0, 3])

In [120]:
a

array([[1, 2, 5, 1, 8, 4, 3],
       [6, 1, 7, 9, 2, 0, 3]])

In [121]:
a.sum()

52

In [122]:
np.dtype('>i4')

dtype('>i4')

In [123]:
np.dtype('>i4').byteorder

'>'

In [124]:
np.dtype('>i4').itemsize

4

In [125]:
np.dtype('>i4').name

'int32'

In [126]:
np.dtype('>i4').type

numpy.int32

In [127]:
np.dtype('>i4').type is np.int32

True

In [128]:
dt = np.dtype([('name', np.unicode_, 16), ('grade', np.float64, (2,))])
dt

dtype([('name', '<U16'), ('grade', '<f8', (2,))])

In [130]:
x

array([('Sarah', [4., 5.]), ('Amir', [3., 7.])],
      dtype=[('name', '<U16'), ('grade', '<f8', (2,))])

In [131]:
x[0]

('Sarah', [4., 5.])

In [132]:
x[0]['grade']

array([4., 5.])

In [133]:
np.complex128

numpy.complex128

In [136]:
complex.__doc__

'Create a complex number from a real part and an optional imaginary part.\n\nThis is equivalent to (real + imag*1j) where imag defaults to 0.'

In [137]:
complex(3.4454)

(3.4454+0j)

In [140]:
np.dtype(int) == np.int32

True

In [139]:
np.dtype(float)

dtype('float64')

In [141]:
np.array(['amir', 'sarah', 'reza'], dtype=str)

array(['amir', 'sarah', 'reza'], dtype='<U5')

In [142]:
np.array(['amir', 'sarah', 'reza'], dtype=str).itemsize

20

In [143]:
a.tobytes()

b'\x01\x00\x00\x00\x02\x00\x00\x00\x05\x00\x00\x00\x01\x00\x00\x00\x08\x00\x00\x00\x04\x00\x00\x00\x03\x00\x00\x00\x06\x00\x00\x00\x01\x00\x00\x00\x07\x00\x00\x00\t\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00'

In [150]:
x = np.empty( (2,), dtype=('i4, f4, U10') )

In [151]:
x[:] = [(123,123,'13'), (123,123,'1232')]

In [152]:
x

array([(123, 123., '13'), (123, 123., '1232')],
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', '<U10')])

In [154]:
x[0]

(123, 123., '13')

In [155]:
x['f0']

array([123, 123])

In [157]:
np.empty((2), dtype='3i8, (3,4)f8')

array([([      2258754946472,                 208,                   0], [[0.00000000e+000, 0.00000000e+000, 5.02034658e+175, 1.52078483e-051], [5.24338193e+174, 2.57320246e+184, 9.14240774e-043, 1.53074269e-047], [6.46700306e-144, 3.59751658e+252, 3.96046095e+246, 1.04918621e-153]]),
       ([7881702260482471202, 7310315409582465637, 2318265727211105906], [[9.08366793e+223, 1.52078483e-051, 5.24338193e+174, 2.57320246e+184], [9.14240774e-043, 1.04914795e-153, 1.94918966e-153, 3.93230821e-062], [2.26402178e-076, 2.17698259e-076, 2.59027896e-144, 7.79952704e-143]])],
      dtype=[('f0', '<i8', (3,)), ('f1', '<f8', (3, 4))])

In [158]:
np.ones((2), dtype='3i8, (3,4)f8')

array([([1, 1, 1], [[1., 1., 1., 1.], [1., 1., 1., 1.], [1., 1., 1., 1.]]),
       ([1, 1, 1], [[1., 1., 1., 1.], [1., 1., 1., 1.], [1., 1., 1., 1.]])],
      dtype=[('f0', '<i8', (3,)), ('f1', '<f8', (3, 4))])

In [161]:
x.dtype.names

('f0', 'f1', 'f2')

In [162]:
np.ones((2,3), dtype=[('id', 'i8', (2,3)), ('name', 'U10')])

array([[([[1, 1, 1], [1, 1, 1]], '1'), ([[1, 1, 1], [1, 1, 1]], '1'),
        ([[1, 1, 1], [1, 1, 1]], '1')],
       [([[1, 1, 1], [1, 1, 1]], '1'), ([[1, 1, 1], [1, 1, 1]], '1'),
        ([[1, 1, 1], [1, 1, 1]], '1')]],
      dtype=[('id', '<i8', (2, 3)), ('name', '<U10')])

In [164]:
np.ones((9,), dtype={'names':['id', 'grade'], 'formats':['i4', 'f4']})

array([(1, 1.), (1, 1.), (1, 1.), (1, 1.), (1, 1.), (1, 1.), (1, 1.),
       (1, 1.), (1, 1.)], dtype=[('id', '<i4'), ('grade', '<f4')])

In [165]:
x

array([(123, 123., '13'), (123, 123., '1232')],
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', '<U10')])

In [166]:
x[['f0', 'f1']]

array([(123, 123.), (123, 123.)],
      dtype={'names': ['f0', 'f1'], 'formats': ['<i4', '<f4'], 'offsets': [0, 4], 'itemsize': 48})

In [169]:
names = np.array(
    [
        ('a', 1, 2),
        ('b', 2, 3),
        ('c', 3, 4),
        ('d', 4, 5),
    ],
    dtype=[
        ('name', str, 3),
        ('age', int),
        ('power', int)
    ]
)

names

array([('a', 1, 2), ('b', 2, 3), ('c', 3, 4), ('d', 4, 5)],
      dtype=[('name', '<U3'), ('age', '<i4'), ('power', '<i4')])

In [170]:
names[names['power']==2]['name']

array(['a'], dtype='<U3')

In [171]:
dt = np.datetime64('2012-11-11')
dt

numpy.datetime64('2012-11-11')

In [172]:
dt.dtype

dtype('<M8[D]')

In [174]:
dt = np.datetime64('2012-01-01')
dt

numpy.datetime64('2012-01-01')

In [177]:
np.arange('2012-01-01', '2020-01-01', dtype='<M8[M]')

array(['2012-01', '2012-02', '2012-03', '2012-04', '2012-05', '2012-06',
       '2012-07', '2012-08', '2012-09', '2012-10', '2012-11', '2012-12',
       '2013-01', '2013-02', '2013-03', '2013-04', '2013-05', '2013-06',
       '2013-07', '2013-08', '2013-09', '2013-10', '2013-11', '2013-12',
       '2014-01', '2014-02', '2014-03', '2014-04', '2014-05', '2014-06',
       '2014-07', '2014-08', '2014-09', '2014-10', '2014-11', '2014-12',
       '2015-01', '2015-02', '2015-03', '2015-04', '2015-05', '2015-06',
       '2015-07', '2015-08', '2015-09', '2015-10', '2015-11', '2015-12',
       '2016-01', '2016-02', '2016-03', '2016-04', '2016-05', '2016-06',
       '2016-07', '2016-08', '2016-09', '2016-10', '2016-11', '2016-12',
       '2017-01', '2017-02', '2017-03', '2017-04', '2017-05', '2017-06',
       '2017-07', '2017-08', '2017-09', '2017-10', '2017-11', '2017-12',
       '2018-01', '2018-02', '2018-03', '2018-04', '2018-05', '2018-06',
       '2018-07', '2018-08', '2018-09', '2018-10', 

In [184]:
x = np.arange('2012-01-01', '2020-01-01', dtype='datetime64[M]')

In [181]:
y = np.datetime64('2000-01-01')
y

numpy.datetime64('2000-01-01')

In [182]:
x - y

array([4383, 4414, 4443, 4474, 4504, 4535, 4565, 4596, 4627, 4657, 4688,
       4718, 4749, 4780, 4808, 4839, 4869, 4900, 4930, 4961, 4992, 5022,
       5053, 5083, 5114, 5145, 5173, 5204, 5234, 5265, 5295, 5326, 5357,
       5387, 5418, 5448, 5479, 5510, 5538, 5569, 5599, 5630, 5660, 5691,
       5722, 5752, 5783, 5813, 5844, 5875, 5904, 5935, 5965, 5996, 6026,
       6057, 6088, 6118, 6149, 6179, 6210, 6241, 6269, 6300, 6330, 6361,
       6391, 6422, 6453, 6483, 6514, 6544, 6575, 6606, 6634, 6665, 6695,
       6726, 6756, 6787, 6818, 6848, 6879, 6909, 6940, 6971, 6999, 7030,
       7060, 7091, 7121, 7152, 7183, 7213, 7244, 7274],
      dtype='timedelta64[D]')

In [183]:
(x - y).tolist()

[datetime.timedelta(days=4383),
 datetime.timedelta(days=4414),
 datetime.timedelta(days=4443),
 datetime.timedelta(days=4474),
 datetime.timedelta(days=4504),
 datetime.timedelta(days=4535),
 datetime.timedelta(days=4565),
 datetime.timedelta(days=4596),
 datetime.timedelta(days=4627),
 datetime.timedelta(days=4657),
 datetime.timedelta(days=4688),
 datetime.timedelta(days=4718),
 datetime.timedelta(days=4749),
 datetime.timedelta(days=4780),
 datetime.timedelta(days=4808),
 datetime.timedelta(days=4839),
 datetime.timedelta(days=4869),
 datetime.timedelta(days=4900),
 datetime.timedelta(days=4930),
 datetime.timedelta(days=4961),
 datetime.timedelta(days=4992),
 datetime.timedelta(days=5022),
 datetime.timedelta(days=5053),
 datetime.timedelta(days=5083),
 datetime.timedelta(days=5114),
 datetime.timedelta(days=5145),
 datetime.timedelta(days=5173),
 datetime.timedelta(days=5204),
 datetime.timedelta(days=5234),
 datetime.timedelta(days=5265),
 datetime.timedelta(days=5295),
 datetim

In [185]:
x.tolist()

[datetime.date(2012, 1, 1),
 datetime.date(2012, 2, 1),
 datetime.date(2012, 3, 1),
 datetime.date(2012, 4, 1),
 datetime.date(2012, 5, 1),
 datetime.date(2012, 6, 1),
 datetime.date(2012, 7, 1),
 datetime.date(2012, 8, 1),
 datetime.date(2012, 9, 1),
 datetime.date(2012, 10, 1),
 datetime.date(2012, 11, 1),
 datetime.date(2012, 12, 1),
 datetime.date(2013, 1, 1),
 datetime.date(2013, 2, 1),
 datetime.date(2013, 3, 1),
 datetime.date(2013, 4, 1),
 datetime.date(2013, 5, 1),
 datetime.date(2013, 6, 1),
 datetime.date(2013, 7, 1),
 datetime.date(2013, 8, 1),
 datetime.date(2013, 9, 1),
 datetime.date(2013, 10, 1),
 datetime.date(2013, 11, 1),
 datetime.date(2013, 12, 1),
 datetime.date(2014, 1, 1),
 datetime.date(2014, 2, 1),
 datetime.date(2014, 3, 1),
 datetime.date(2014, 4, 1),
 datetime.date(2014, 5, 1),
 datetime.date(2014, 6, 1),
 datetime.date(2014, 7, 1),
 datetime.date(2014, 8, 1),
 datetime.date(2014, 9, 1),
 datetime.date(2014, 10, 1),
 datetime.date(2014, 11, 1),
 datetime.da

In [186]:
x[0].item()

datetime.date(2012, 1, 1)

In [188]:
import datetime
np.array([datetime.datetime(2011,1,1)], dtype=np.datetime64)

array(['2011-01-01T00:00:00.000000'], dtype='datetime64[us]')

In [190]:
_id = np.arange(1000)
_value = np.random.random(1000)
_date = np.random.randint(0, 365, 1000) + np.datetime64('2020-01-01')

In [192]:
x = np.core.records.fromarrays(
    [_id, _value, _date],
    names='id, value, date',
    formats='i4, f4, a10'
)

In [193]:
np.savetxt('./records.csv', x, fmt='%i, %.4f, %s')

In [194]:

x = np.genfromtxt(
    './records.csv',
    dtype='i4, f4, a10',
    delimiter=',',
    skip_header=0
)


In [195]:
x

array([(  0, 3.363e-01, b" b'2020-01"), (  1, 3.415e-01, b" b'2020-04"),
       (  2, 4.200e-02, b" b'2020-02"), (  3, 2.433e-01, b" b'2020-09"),
       (  4, 2.100e-03, b" b'2020-07"), (  5, 1.264e-01, b" b'2020-05"),
       (  6, 2.657e-01, b" b'2020-04"), (  7, 1.952e-01, b" b'2020-06"),
       (  8, 7.788e-01, b" b'2020-11"), (  9, 9.068e-01, b" b'2020-06"),
       ( 10, 3.172e-01, b" b'2020-07"), ( 11, 5.982e-01, b" b'2020-04"),
       ( 12, 1.163e-01, b" b'2020-11"), ( 13, 3.502e-01, b" b'2020-11"),
       ( 14, 7.134e-01, b" b'2020-08"), ( 15, 7.919e-01, b" b'2020-02"),
       ( 16, 2.879e-01, b" b'2020-04"), ( 17, 6.707e-01, b" b'2020-05"),
       ( 18, 1.695e-01, b" b'2020-08"), ( 19, 5.240e-01, b" b'2020-01"),
       ( 20, 4.419e-01, b" b'2020-12"), ( 21, 7.211e-01, b" b'2020-10"),
       ( 22, 2.294e-01, b" b'2020-07"), ( 23, 4.031e-01, b" b'2020-02"),
       ( 24, 9.990e-01, b" b'2020-02"), ( 25, 7.969e-01, b" b'2020-11"),
       ( 26, 6.301e-01, b" b'2020-10"), ( 27, 6.550

In [196]:
x.dtype

dtype([('f0', '<i4'), ('f1', '<f4'), ('f2', 'S10')])

In [197]:
x.dtype.names = 'id', 'value', 'date'
x

array([(  0, 3.363e-01, b" b'2020-01"), (  1, 3.415e-01, b" b'2020-04"),
       (  2, 4.200e-02, b" b'2020-02"), (  3, 2.433e-01, b" b'2020-09"),
       (  4, 2.100e-03, b" b'2020-07"), (  5, 1.264e-01, b" b'2020-05"),
       (  6, 2.657e-01, b" b'2020-04"), (  7, 1.952e-01, b" b'2020-06"),
       (  8, 7.788e-01, b" b'2020-11"), (  9, 9.068e-01, b" b'2020-06"),
       ( 10, 3.172e-01, b" b'2020-07"), ( 11, 5.982e-01, b" b'2020-04"),
       ( 12, 1.163e-01, b" b'2020-11"), ( 13, 3.502e-01, b" b'2020-11"),
       ( 14, 7.134e-01, b" b'2020-08"), ( 15, 7.919e-01, b" b'2020-02"),
       ( 16, 2.879e-01, b" b'2020-04"), ( 17, 6.707e-01, b" b'2020-05"),
       ( 18, 1.695e-01, b" b'2020-08"), ( 19, 5.240e-01, b" b'2020-01"),
       ( 20, 4.419e-01, b" b'2020-12"), ( 21, 7.211e-01, b" b'2020-10"),
       ( 22, 2.294e-01, b" b'2020-07"), ( 23, 4.031e-01, b" b'2020-02"),
       ( 24, 9.990e-01, b" b'2020-02"), ( 25, 7.969e-01, b" b'2020-11"),
       ( 26, 6.301e-01, b" b'2020-10"), ( 27, 6.550

In [198]:
np.save('x.npy', x, allow_pickle=False)

In [199]:
x = np.load('./x.npy')
x

array([(  0, 3.363e-01, b" b'2020-01"), (  1, 3.415e-01, b" b'2020-04"),
       (  2, 4.200e-02, b" b'2020-02"), (  3, 2.433e-01, b" b'2020-09"),
       (  4, 2.100e-03, b" b'2020-07"), (  5, 1.264e-01, b" b'2020-05"),
       (  6, 2.657e-01, b" b'2020-04"), (  7, 1.952e-01, b" b'2020-06"),
       (  8, 7.788e-01, b" b'2020-11"), (  9, 9.068e-01, b" b'2020-06"),
       ( 10, 3.172e-01, b" b'2020-07"), ( 11, 5.982e-01, b" b'2020-04"),
       ( 12, 1.163e-01, b" b'2020-11"), ( 13, 3.502e-01, b" b'2020-11"),
       ( 14, 7.134e-01, b" b'2020-08"), ( 15, 7.919e-01, b" b'2020-02"),
       ( 16, 2.879e-01, b" b'2020-04"), ( 17, 6.707e-01, b" b'2020-05"),
       ( 18, 1.695e-01, b" b'2020-08"), ( 19, 5.240e-01, b" b'2020-01"),
       ( 20, 4.419e-01, b" b'2020-12"), ( 21, 7.211e-01, b" b'2020-10"),
       ( 22, 2.294e-01, b" b'2020-07"), ( 23, 4.031e-01, b" b'2020-02"),
       ( 24, 9.990e-01, b" b'2020-02"), ( 25, 7.969e-01, b" b'2020-11"),
       ( 26, 6.301e-01, b" b'2020-10"), ( 27, 6.550

In [201]:
np.savez('x_a.npz', x, a)

In [208]:
x_a = np.load('./x_a.npz')
x_a

NpzFile './x_a.npz' with keys: arr_0, arr_1

In [204]:
x

'arr_0'

In [205]:
a

'arr_1'

In [207]:
x_a['arr_0']

array([(  0, 3.363e-01, b" b'2020-01"), (  1, 3.415e-01, b" b'2020-04"),
       (  2, 4.200e-02, b" b'2020-02"), (  3, 2.433e-01, b" b'2020-09"),
       (  4, 2.100e-03, b" b'2020-07"), (  5, 1.264e-01, b" b'2020-05"),
       (  6, 2.657e-01, b" b'2020-04"), (  7, 1.952e-01, b" b'2020-06"),
       (  8, 7.788e-01, b" b'2020-11"), (  9, 9.068e-01, b" b'2020-06"),
       ( 10, 3.172e-01, b" b'2020-07"), ( 11, 5.982e-01, b" b'2020-04"),
       ( 12, 1.163e-01, b" b'2020-11"), ( 13, 3.502e-01, b" b'2020-11"),
       ( 14, 7.134e-01, b" b'2020-08"), ( 15, 7.919e-01, b" b'2020-02"),
       ( 16, 2.879e-01, b" b'2020-04"), ( 17, 6.707e-01, b" b'2020-05"),
       ( 18, 1.695e-01, b" b'2020-08"), ( 19, 5.240e-01, b" b'2020-01"),
       ( 20, 4.419e-01, b" b'2020-12"), ( 21, 7.211e-01, b" b'2020-10"),
       ( 22, 2.294e-01, b" b'2020-07"), ( 23, 4.031e-01, b" b'2020-02"),
       ( 24, 9.990e-01, b" b'2020-02"), ( 25, 7.969e-01, b" b'2020-11"),
       ( 26, 6.301e-01, b" b'2020-10"), ( 27, 6.550

In [209]:
np.matrix(np.arange(9).reshape(3, 3))

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [210]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [211]:

np.matrix('1 2 3; 4 5 6; 7 8 9')

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [212]:
np.matrix([[1,2,3],[4,5,6],[7,8,9]])


matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [213]:
a

'arr_1'

In [214]:
x

'arr_0'

In [215]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [216]:
np.dot(x,x)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [217]:
x.I

AttributeError: 'numpy.ndarray' object has no attribute 'I'

In [221]:
x  = np.matrix(x)
x.H

matrix([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [222]:
A = np.mat('3 1 4; 1 5 9; 2 6 5')
b = np.mat([[1], [2], [3]])
x = A.I * b

In [223]:
x

matrix([[ 0.26666667],
        [ 0.46666667],
        [-0.06666667]])

In [224]:
A * x

matrix([[1.],
        [2.],
        [3.]])

In [225]:
b

matrix([[1],
        [2],
        [3]])

In [226]:
A * x == b

matrix([[False],
        [False],
        [ True]])

In [227]:
np.allclose(A * x, b)

True

In [228]:
A.A

array([[3, 1, 4],
       [1, 5, 9],
       [2, 6, 5]])

In [230]:
A.A1

array([3, 1, 4, 1, 5, 9, 2, 6, 5])

In [231]:
np.outer(x, y)

UFuncTypeError: ufunc 'multiply' cannot use operands with types dtype('float64') and dtype('<M8[D]')

In [232]:
np.outer(
    np.array([[1], [2], [3]]),
    np.array([[10], [20], [30]]),
)

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [233]:
np.outer(
    np.array([[1], [2], [3]]),
    np.array([[10], [20]]),
)

array([[10, 20],
       [20, 40],
       [30, 60]])

In [234]:
np.outer(
    np.array([[1], [2]]),
    np.array([[10], [20], [30]]),
)

array([[10, 20, 30],
       [20, 40, 60]])

In [235]:
np.outer(
    np.array([[10], [20], [30]]),
    np.array([[1], [2]]),
)

array([[10, 20],
       [20, 40],
       [30, 60]])

In [236]:
np.cross(
    [1,2,3],
    [2,3,4]
)

array([-1,  2, -1])

In [237]:
np.linalg

<module 'numpy.linalg' from 'd:\\dev\\venv\\Lib\\site-packages\\numpy\\linalg\\__init__.py'>

In [238]:
np.linalg.det(A)

-90.0

In [239]:
A

matrix([[3, 1, 4],
        [1, 5, 9],
        [2, 6, 5]])

In [240]:
np.linalg.inv(A)

matrix([[ 0.32222222, -0.21111111,  0.12222222],
        [-0.14444444, -0.07777778,  0.25555556],
        [ 0.04444444,  0.17777778, -0.15555556]])

In [242]:
np.matrix(A).I

matrix([[ 0.32222222, -0.21111111,  0.12222222],
        [-0.14444444, -0.07777778,  0.25555556],
        [ 0.04444444,  0.17777778, -0.15555556]])

In [243]:
np.linalg.solve(A, b)

matrix([[ 0.26666667],
        [ 0.46666667],
        [-0.06666667]])

In [244]:
np.linalg.svd(A)

SVDResult(U=matrix([[-0.32463251, -0.79898436, -0.50619929],
        [-0.75307473, -0.1054674 ,  0.64942672],
        [-0.57226932,  0.59203093, -0.56745679]]), S=array([13.58235799,  2.84547726,  2.32869289]), Vh=matrix([[-0.21141476, -0.55392606, -0.80527617],
        [-0.46331722,  0.78224635, -0.41644663],
        [-0.86060499, -0.28505536,  0.42202191]]))

In [245]:
np.diag(A)

array([3, 5, 5])

In [246]:
np.diag(4)

ValueError: Input must be 1- or 2-d.

In [247]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [248]:
np.diag([[1,2],[3,4]])

array([1, 4])

In [249]:
np.poly == np.polynomial

False

In [252]:
np.poly.__doc__

'\n    Find the coefficients of a polynomial with the given sequence of roots.\n\n    .. note::\n       This forms part of the old polynomial API. Since version 1.4, the\n       new polynomial API defined in `numpy.polynomial` is preferred.\n       A summary of the differences can be found in the\n       :doc:`transition guide </reference/routines.polynomials>`.\n\n    Returns the coefficients of the polynomial whose leading coefficient\n    is one for the given sequence of zeros (multiple roots must be included\n    in the sequence as many times as their multiplicity; see Examples).\n    A square matrix (or array, which will be treated as a matrix) can also\n    be given, in which case the coefficients of the characteristic polynomial\n    of the matrix are returned.\n\n    Parameters\n    ----------\n    seq_of_zeros : array_like, shape (N,) or (N, N)\n        A sequence of polynomial roots, or a square array or matrix object.\n\n    Returns\n    -------\n    c : ndarray\n        1D 

In [253]:
np.polynomial.__doc__

'\nA sub-package for efficiently dealing with polynomials.\n\nWithin the documentation for this sub-package, a "finite power series,"\ni.e., a polynomial (also referred to simply as a "series") is represented\nby a 1-D numpy array of the polynomial\'s coefficients, ordered from lowest\norder term to highest.  For example, array([1,2,3]) represents\n``P_0 + 2*P_1 + 3*P_2``, where P_n is the n-th order basis polynomial\napplicable to the specific module in question, e.g., `polynomial` (which\n"wraps" the "standard" basis) or `chebyshev`.  For optimal performance,\nall operations on polynomials, including evaluation at an argument, are\nimplemented as operations on the coefficients.  Additional (module-specific)\ninformation can be found in the docstring for the module of interest.\n\nThis package provides *convenience classes* for each of six different kinds\nof polynomials:\n\n         ========================    ================\n         **Name**                    **Provides**\n     

In [254]:
np.poly(np.array([1,2,3,4]))

array([  1., -10.,  35., -50.,  24.])

In [255]:
np.roots(np.array([1,2,3,4]))

array([-1.65062919+0.j        , -0.1746854 +1.54686889j,
       -0.1746854 -1.54686889j])

In [256]:
np.polyval(np.array([1,2,3,4]), 5)

194

In [257]:
np.polyint(np.array([1,2,3,4]))

array([0.25      , 0.66666667, 1.5       , 4.        , 0.        ])

In [261]:
np.polyder(np.polyint(np.array([1,2,3,4]))) == np.array([1,2,3,4])

array([ True,  True,  True,  True])